### ISSUE TITLE
Question about decoupled instance depth

### ISSUE THREAD

**Issue by Senwang98** [SPengLiang/DID-M3D#9]
@SPengLiang 
Hi, I meet one question when reading your code.
In datasets/kitti.py processing, I print `roi_depth_ind` and `att_depth[i]`.
I also visualize the bbox2d in image as following:
![res](https://user-images.githubusercontent.com/23122139/184531192-4dc0285f-bce2-4a1b-819d-6e7d6495e6da.jpg)

The `roi_depth_ind` equals:
```
[[False, True, True, True, True, True, False],
 [True, True, True, True, True, True, True],
 [True, True, True, True, True, True, True],
 [True, True, True, True, True, True, True],
 [True, True, True, True, True, True, True],
 [True, True, True, True, True, True, True],
 [True, True, False, False, False, False, True]]
```

The `att_depth[i] * roi_depth_ind` equals:
```
0.00    -0.82   -1.09   -1.66   -1.26   -1.16   0.00    
-0.99   -0.39   -0.15   -0.37   -0.57   -0.80   -2.28   
-2.79   -0.20   0.04    0.14    0.22    0.11    -1.82   
-0.90   0.07    0.17    0.19    0.20    0.25    -1.11   
-0.29   -0.50   -0.44   -0.30   -0.38   -0.16   0.10    
0.41    0.23    0.43    0.50    0.40    0.35    0.53    
2.93    2.97    0.00    0.00    0.00    0.00    2.97  
```

Q1: There are some negative numbers in depth[i]. Do you think this situation is consistent with the original intention of attribute depth design? (namely, is the existence of negative numbers consistent with the physical meaning, especially when the vehicle is inclined)

Q2: As shown above, I found a picture of the back of the vehicle (90 degree). Theoretically, it should be positive at this time, but in fact, there are negative numbers depth. Do you think these negative numbers are caused by the point cloud completion algorithm of ICRA?

Q3: I modified the following codes in 'kitti.py', the number less than 0 is prohibited. However, I found the performance is always less than `16 mAP`.(using your code, I can even get 17.44 val mAP, which is better than 17.02 you provide), I feel confused about such performance gap.
```
roi_depth_ind = (roi_depth > depth[i] - 3) & \
                            (roi_depth < depth[i]) & \
                            (roi_depth > 0)
```

**Comment by SPengLiang** [comment]
Q1: the proposed attribute depth is different from the typical depth. Attribute depth refers to the depth offset from the object surface to its center depth. So it is reasonable that att_depth contain negative numbers (negative numbers are consistent with the physical meaning).

Q2: In your case, most valid att_depth should be negative (because car tail depth - car center depth < 0). These negative number are reasonable.

Q3:  If you remove the negative numbers in attribute depth, the model cannot learn the complete attribute depth, thus the overall perfoamance will decrease (BTW, we trained the model using the code three times and the relased model is not the best one, because we want to make sure the reproducibility of this codebase).

Hope this can help you, and feel free if you have further questions.

**Comment by Senwang98** [comment]
Okay, I  have no other question about Q1 and Q3.
But, for Q2, I don't think so.
In kitti.py, you use `att_depth[i] = depth[i] - vis_depth[i]` to get att_depth.
In this condition, the att_dep should be positive.
(我觉得这种正对相机的车辆，按照code中的计算，应该是中心框深度减去lidar的深度，不应该是正数吗，其中出现了负数，我在想是不是因为插值算法导致的还是lidar成像原理导致的？)

**Comment by SPengLiang** [comment]
Thanks for your feedback. I reviewed the code and agree with you. Can you provide this file index in KITTI (e.g. xxxxxx.png)? I will check it and give you feedback.

**Comment by Senwang98** [comment]
@SPengLiang 
Wait a moment, I used train command to run, so the image idx is **random**.
But, I think I can find another one which have the same question.

**Comment by Senwang98** [comment]
@SPengLiang 
I found one, training/image_2/1426.png.
```
  -     -   -1.79   -     -     -     -   -2.39   -     -     -     -     -   
  -     -   -0.63 -1.13 -1.39 -1.38 -1.15 -0.80 -0.14 -2.27   -     -     -   
  -   -2.25 -0.84 -1.13 -1.24 -1.21 -1.09 -0.94 -0.54 -0.62   -     -     -   
  -   -0.47 -0.40 -0.48 -0.53 -0.54 -0.50 -0.42 -0.25 0.07  -2.16   -     -   
0.14  0.24  0.19  0.25  0.24  0.18  0.16  0.25  0.26  0.37  0.40    -     -   
0.34  0.31  0.26  0.23  0.22  0.22  0.26  0.37  0.47  0.61  0.59  -2.42   -   
0.52  0.42  0.33  0.25  0.20  0.20  0.26  0.41  0.54  0.72  0.77  -1.39   -   
0.66  0.53  0.37  0.25  0.16  0.11  0.16  0.33  0.48  0.71  0.89  -0.31   -   
0.58  0.41  0.14  -0.01 -0.16 -0.28 -0.35 -0.32 -0.11 0.27  0.60  -0.22   -   
0.30  0.11  -0.23 -0.36 -0.56 -0.70 -0.76 -0.73 -0.58 -0.19 0.24  -0.19   -   
-0.13 -0.32 -0.69 -0.75 -0.99 -1.12 -1.07 -0.91 -0.95 -0.63 -0.16 -0.19 -2.41 
0.02  -0.12 -0.29 -0.27 -0.33 -0.35 -0.29 -0.20 -0.24 -0.10 0.17  0.26  -0.78 
0.81  0.74  0.71  0.77  0.80  0.83  0.87  0.90  0.86  0.88  0.99  1.08  0.79  
```
<img width="871" alt="image" src="https://user-images.githubusercontent.com/23122139/184534609-1ab38df4-085d-4469-b703-5ac78fcec636.png">

**Comment by SPengLiang** [comment]
Thanks for your reply. I make sure that the reason lies in the inaccurate corresponding depth patch. You are right, these inaccurate depths are caused by the depth completion algorithm. 
Actually, most depth completion algorithms are trained on KITTI, where KITTI depth completion labels are accumulated by ICP between multiple consecutive frames. Although KITTI filters out some outliers by stereo matching, the labels of moving objects that are not close cannot be precisely obtained. You can visualize such depth completion labels and find some cases, here I can give two examples. (This is another long story ....)

<img width="403" alt="image" src="https://user-images.githubusercontent.com/14855845/184536041-3ee4bdd9-3227-45ea-9947-790761184766.png">

**Comment by Senwang98** [comment]
@SPengLiang 
Okay, I got it. thanks for your reply.
Good luck
